version: 2
updates:
  - package-ecosystem: nuget
    directory: "/sdk"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
  - package-ecosystem: gomod
    directory: "/src"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
